version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: oauth2_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=oauth2_demo
      - JWT_SECRET=your-super-secret-key-change-in-production
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: